### ISSUE TITLE
Wrong generated ts result code

### ISSUE THREAD

**Issue by Zercerium** [tauri-apps/tauri-bindgen#143]
The generated ts code from this function `func test(a: string) -> result<string, string>` has a bug.

At the moment you will get an `Unhandled Promise Rejection: Error: Deserialize bad result undefined` thrown.

the following ts code is generated in the test function:
```
return deserializeResult(
        de,
        deserializeString(de),
        deserializeString(de)
      );
```

instead it should be generated:
```
return deserializeResult(
        de,
        deserializeString,
        deserializeString
      );
```

also the `deserializeResult` function has a small bug

generated code:
```
switch (tag) {
    case 0:
      return { Ok: ok(de) };
    case 1:
      return { Err: err(de) };
    default:
      throw new Error(`Deserialize bad result ${tag}`);
  }
```

instead it should be generated:
```
switch (tag) {
    case 0:
      return { tag: 'ok', val: ok(de) };
    case 1:
      return { tag: 'err', val: err(de) };
    default:
      throw new Error(`Deserialize bad result ${tag}`);
  }
```
if you want to match the current type definition of `Result`

using v0.2.0 installed via cargo install

**Comment by JonasKruckenberg** [comment]
closed by #144
